### ISSUE TITLE
Simplify CSS code for the font-weight property.

### ISSUE THREAD

**Issue by josephtkim** [Sakrostudio/prj-rev-bwfs-dasmoto#5]
Great job simplifying the CSS code for several of the shared properties. You can simplify it further for the font-weight property, like so 

```css
h1, h2, a {
  font-weight: bold;
}
```
